Repository AiKU-Dev/Backend, pull requests merged in 2024-12, with the labels that each got.

#130 feat : ScheduleService에서 스케줄 관련 알람을 보내기 위한 카프카 메세지 구조 변경 적용
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/ScheduleAlarmMessage.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
Labels: 기능개발

#134 RT 및 약관 전달 방식 변경
  aiku/aiku-main/src/main/java/aiku_main/controller/LoginController.java
  aiku/aiku-main/src/main/java/aiku_main/controller/TermController.java
  aiku/aiku-main/src/main/java/aiku_main/dto/RefreshTokenDto.java
  aiku/aiku-main/src/main/java/aiku_main/service/TermService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TermServiceTest.java
Labels: 리팩토링

#135 Team관련 기능 검증 및 보강, 리팩토링
  aiku/aiku-common/src/main/java/common/domain/team/Team.java
  aiku/aiku-common/src/main/java/common/domain/team/TeamMember.java
  aiku/aiku-common/src/main/java/common/domain/team/TeamResult.java
  aiku/aiku-common/src/main/java/common/util/ObjectMapperUtil.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/TeamHandler.java
  aiku/aiku-main/src/main/java/aiku_main/controller/ScheduleController.java
  aiku/aiku-main/src/main/java/aiku_main/controller/TeamController.java
  aiku/aiku-main/src/main/java/aiku_main/dto/TeamDetailResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/TeamMemberResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/TeamAddDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/TeamBettingResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/TeamDetailResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/TeamLateTimeResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/TeamMemberResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/TeamMemberResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/TeamRacingResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/TeamResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/TeamScheduleListEachResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/TeamScheduleListResDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/MemberRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamQueryRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamQueryRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamQueryRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java
  aiku/aiku-main/src/test/java/aiku_main/controller/TeamControllerTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TeamServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/TeamServiceTest.java
Labels: 기능개발, 리팩토링

#137 파이어베이스 토큰 테스트 오류 해결
  aiku/aiku-main/src/main/java/aiku_main/service/MemberFirebaseService.java
Labels: 빌드수정

#138 수정사항 반영
  aiku/aiku-main/src/main/java/aiku_main/service/MemberFirebaseService.java
Labels: 배포

#139 리스트 전달 방식 변경
  aiku/aiku-alarm/src/main/java/alarm/controller/MemberMessageController.java
  aiku/aiku-alarm/src/main/java/alarm/controller/dto/DataResDto.java
  aiku/aiku-alarm/src/main/java/alarm/repository/MemberMessageRepository.java
  aiku/aiku-alarm/src/main/java/alarm/service/MemberMessageService.java
  aiku/aiku-alarm/src/main/resources/application.yml
Labels: 버그수정

#140 안드로이드 인앱 결제 로직 작성
  aiku/aiku-alarm/src/main/java/alarm/util/AlarmMessageConverter.java
  aiku/aiku-alarm/src/main/java/alarm/util/AlarmMessageMapper.java
  aiku/aiku-common/src/main/java/common/domain/Payment.java
  aiku/aiku-common/src/main/java/common/domain/PaymentProduct.java
  aiku/aiku-common/src/main/java/common/domain/PaymentProductType.java
  aiku/aiku-common/src/main/java/common/domain/PaymentStatus.java
  aiku/aiku-common/src/main/java/common/kafka_message/PaymentPointChangedMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/PaymentPointSagaMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/PaymentPointStatus.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/AlarmMessageType.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/PaymentFailedMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/PaymentSuccessMessage.java
  aiku/aiku-common/src/main/java/common/response/status/BaseErrorCode.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/PaymentPointChangeEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/PointChangeEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/PointChangeReason.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/PointChangeEventHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/PointChangeEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/kafka/KafkaConsumerService.java
  aiku/aiku-main/src/main/java/aiku_main/service/PaymentPointMessageHelper.java
  aiku/aiku-main/src/main/java/aiku_main/service/PointLogFactory.java
  aiku/aiku-payment/build.gradle
  aiku/aiku-payment/src/main/java/payment/controller/PaymentController.java
  aiku/aiku-payment/src/main/java/payment/controller/dto/PurchaseRequest.java
  aiku/aiku-payment/src/main/java/payment/controller/dto/PurchaseVerificationResponse.java
  aiku/aiku-payment/src/main/java/payment/exception/MemberNotFoundException.java
  aiku/aiku-payment/src/main/java/payment/exception/PaymentException.java
  aiku/aiku-payment/src/main/java/payment/exception/PaymentExceptionHandler.java
  aiku/aiku-payment/src/main/java/payment/kafka/KafkaConsumerService.java
  aiku/aiku-payment/src/main/java/payment/kafka/KafkaProducerService.java
  aiku/aiku-payment/src/main/java/payment/repository/MemberRepository.java
  aiku/aiku-payment/src/main/java/payment/repository/PaymentProductCustomRepository.java
  aiku/aiku-payment/src/main/java/payment/repository/PaymentProductCustomRepositoryImpl.java
  aiku/aiku-payment/src/main/java/payment/repository/PaymentProductRepository.java
  aiku/aiku-payment/src/main/java/payment/service/GooglePaymentHelper.java
  aiku/aiku-payment/src/main/java/payment/service/PaymentService.java
  aiku/aiku-payment/src/main/java/payment/service/PaymentServiceHelper.java
  aiku/aiku-payment/src/main/java/payment/util/AccessTokenProvider.java
  aiku/aiku-payment/src/main/java/payment/util/GoogleConfig.java
  aiku/aiku-payment/src/main/resources/application.yml
  aiku/aiku-payment/src/test/java/aiku_payment/payment_test/PaymentServiceTest.java
Labels: 기능개발

#142 FCM 토큰 저장 방식 변경
  aiku/aiku-main/src/main/java/aiku_main/controller/FirebaseController.java
  aiku/aiku-main/src/main/java/aiku_main/service/MemberFirebaseService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/MemberFirebaseServiceTest.java
Labels: 기능개발, 리팩토링

#144 스케줄 종료 시 레이싱 결과 저장 방식 변경
  aiku/aiku-main/src/main/java/aiku_main/application_event/domain/ScheduleRacing.java
  aiku/aiku-main/src/main/java/aiku_main/service/RacingService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/RacingServiceTest.java
Labels: 리팩토링

#146 환경 변수 대신 파일을 이용하도록 수정
  .gitignore
  aiku/aiku-alarm/src/main/java/alarm/fcm/FirebaseConfig.java
  aiku/aiku-alarm/src/main/java/alarm/fcm/FirebaseInitializer.java
  aiku/aiku-alarm/src/main/resources/application.yml
Labels: 리팩토링

#149 메인에서 결제 관련 불필요한 코드 삭제
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/PaymentPointChangeEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/PointChangeReason.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/PointChangeEventHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/PointChangeEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/kafka/KafkaConsumerService.java
  aiku/aiku-main/src/main/java/aiku_main/service/PaymentPointMessageHelper.java
  aiku/aiku-main/src/main/java/aiku_main/service/PointLogFactory.java
Labels: 리팩토링

#151 기획 변경에 따른 Schedule도메인 로직 수정 및 리팩토링
  aiku/aiku-common/src/main/java/common/domain/schedule/Schedule.java
  aiku/aiku-common/src/main/java/common/domain/schedule/ScheduleMember.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/TeamValue.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/ScheduleAlarmMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/ScheduleMemberAlarmMessage.java
  aiku/aiku-common/src/main/java/common/response/status/BaseErrorCode.java
  aiku/aiku-main/src/main/java/aiku_main/controller/ScheduleController.java
  aiku/aiku-main/src/main/java/aiku_main/dto/ScheduleEnterDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/MemberScheduleListEachResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/MemberScheduleListResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/ScheduleAddDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/ScheduleDetailResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/ScheduleMemberResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/ScheduleUpdateDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/TeamScheduleListEachResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/TeamScheduleListResDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamQueryRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamQueryRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/resources/application.yml
  aiku/aiku-main/src/main/resources/service-info.yml
  aiku/aiku-main/src/test/java/aiku_main/controller/ScheduleControllerTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/BettingServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/MemberFirebaseServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/MemberRegisterServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/MemberServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/PointChangeEventTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/RacingServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/ScheduleServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/TeamServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/TeamServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/TermServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/TitleServiceTest.java
Labels: 기능개발, 리팩토링

#152 스케줄 프리뷰 조회 기능 개발
  aiku/aiku-main/src/main/java/aiku_main/controller/ScheduleController.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/ScheduleOwnerResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/SchedulePreviewResDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/test/java/aiku_main/service/ScheduleServiceTest.java
Labels: 기능개발
