Repository AiKU-Dev/Backend, pull requests merged in 2024-11, with the labels that each got.

#94 스케줄 상세 조회, 그룹 분석 디자인에 맞춰 기능 보강
  aiku/aiku-main/src/main/java/aiku_main/application_event/domain/TeamLateTimeResult.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/domain/TeamResultMember.java
  aiku/aiku-main/src/main/java/aiku_main/dto/ScheduleMemberResDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TeamServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/ScheduleServiceTest.java
Labels: 기능개발

#95 스케줄 상세 조회, 그룹 지각 분석, 그룹 베팅 분석 기능 보강 배포
  aiku/aiku-common/src/main/java/common/response/status/BaseErrorCode.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/domain/TeamLateTimeResult.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/domain/TeamResultMember.java
  aiku/aiku-main/src/main/java/aiku_main/dto/ScheduleMemberResDto.java
  aiku/aiku-main/src/main/java/aiku_main/exception/FcmException.java
  aiku/aiku-main/src/main/java/aiku_main/exception/FcmTokenDuplicateException.java
  aiku/aiku-main/src/main/java/aiku_main/exception/MainExceptionHandler.java
  aiku/aiku-main/src/main/java/aiku_main/exception/TermException.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/MemberFirebaseService.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TermService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/MemberFirebaseServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TeamServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TermServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/ScheduleServiceTest.java
  aiku/aiku-map/src/main/java/map/exception/DuplicateRacingException.java
  aiku/aiku-map/src/main/java/map/exception/MapExceptionHandler.java
  aiku/aiku-map/src/main/java/map/exception/NoSuchRacingException.java
  aiku/aiku-map/src/main/java/map/exception/RacingException.java
  aiku/aiku-map/src/main/java/map/scheduler/RacingScheduler.java
  aiku/aiku-map/src/main/java/map/service/RacingService.java
  aiku/aiku-map/src/test/java/map/service/RacingServiceTest.java
Labels: 배포

#100 지정된 달에서 스케줄이 있는 날짜 반환 기능 개발 및 그 외 기능 보강
  aiku/aiku-main/src/main/java/aiku_main/controller/ScheduleController.java
  aiku/aiku-main/src/main/java/aiku_main/dto/MonthDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/ScheduleDetailResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/SearchDateCond.java
  aiku/aiku-main/src/main/java/aiku_main/dto/SimpleResDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java
  aiku/aiku-main/src/test/java/aiku_main/controller/ScheduleControllerTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TeamServiceIntegrationTest.java
Labels: 기능개발, 리팩토링

#102 영속성 관리 문제로 인한 테스트 실패 해결
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TeamServiceIntegrationTest.java
Labels: 버그수정

#103 배포를 위한 테스트 오류 수정
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TeamServiceIntegrationTest.java
Labels: 버그수정, 배포

#105 /member/schedules의 하위 경로 라우팅 설정
  aiku/aiku-gateway/src/main/resources/application.yml
Labels: 기능개발

#106 게이트 웨이 라우팅 경로 수정 배포
  aiku/aiku-gateway/src/main/resources/application.yml
Labels: 배포

#108 맵의 스케줄 상세 조회 기능 개발 및 테스트
  aiku/aiku-map/src/main/java/map/controller/MapController.java
  aiku/aiku-map/src/main/java/map/dto/LocationResDto.java
  aiku/aiku-map/src/main/java/map/dto/MemberProfileDto.java
  aiku/aiku-map/src/main/java/map/dto/ScheduleDetailResDto.java
  aiku/aiku-map/src/main/java/map/dto/ScheduleMemberResDto.java
  aiku/aiku-map/src/main/java/map/repository/ScheduleQueryRepository.java
  aiku/aiku-map/src/main/java/map/repository/ScheduleQueryRepositoryImpl.java
  aiku/aiku-map/src/main/java/map/service/MapService.java
  aiku/aiku-map/src/test/java/map/service/MapServiceTest.java
Labels: 기능개발

#113 ExceptionHandler에서 ResponseEntity 반환
  aiku/aiku-common/src/main/java/common/response/BaseErrorResponse.java
  aiku/aiku-main/src/main/java/aiku_main/exception/MainExceptionHandler.java
  aiku/aiku-map/src/main/java/map/exception/MapExceptionHandler.java
Labels: 버그수정

#114 모든 응답의 HttpStatusCode가 200으로 나가는 문제 해결, 배포
  aiku/aiku-common/src/main/java/common/domain/member/Member.java
  aiku/aiku-common/src/main/java/common/domain/title/Title.java
  aiku/aiku-common/src/main/java/common/domain/title/TitleCode.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/TitleMemberValue.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/AlarmMessageType.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/TitleGrantedMessage.java
  aiku/aiku-common/src/main/java/common/response/BaseErrorResponse.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/TitleHandler.java
  aiku/aiku-main/src/main/java/aiku_main/controller/MemberController.java
  aiku/aiku-main/src/main/java/aiku_main/exception/MainExceptionHandler.java
  aiku/aiku-main/src/main/java/aiku_main/repository/MemberQueryRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/MemberQueryRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/MemberRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TitleQueryRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TitleQueryRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TitleQueryRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/MemberService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TitleService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/MemberServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TitleServiceTest.java
  aiku/aiku-map/src/main/java/map/controller/MapController.java
  aiku/aiku-map/src/main/java/map/dto/LocationResDto.java
  aiku/aiku-map/src/main/java/map/dto/MemberProfileDto.java
  aiku/aiku-map/src/main/java/map/dto/ScheduleDetailResDto.java
  aiku/aiku-map/src/main/java/map/dto/ScheduleMemberResDto.java
  aiku/aiku-map/src/main/java/map/exception/MapExceptionHandler.java
  aiku/aiku-map/src/main/java/map/repository/ScheduleQueryRepository.java
  aiku/aiku-map/src/main/java/map/repository/ScheduleQueryRepositoryImpl.java
  aiku/aiku-map/src/main/java/map/service/MapService.java
  aiku/aiku-map/src/test/java/map/service/MapServiceTest.java
Labels: 배포

#116 aiku-gateway에 login/refresh 라우팅 경로 추가 및 ddl auto create 설정
  aiku/aiku-gateway/src/main/resources/application.yml
Labels: 빌드수정

#118 aiku-main의 ddl-auto create으로 변경
  aiku/aiku-gateway/src/main/resources/application.yml
  aiku/aiku-main/src/main/resources/application.yml
Labels: 빌드수정

#119 db 초기화를 위한 배포
  aiku/aiku-gateway/src/main/resources/application.yml
  aiku/aiku-main/src/main/resources/application.yml
Labels: 배포

#121 로그인 시 멤버 RT를 저장하지 않는 문제 해결
  aiku/aiku-main/src/main/java/aiku_main/service/LoginService.java
Labels: 버그수정

#124 멤버 탈퇴 시 실제 DB 상 삭제가 아닌 필드 수정
  aiku/aiku-common/src/main/java/common/domain/member/Member.java
  aiku/aiku-main/src/main/java/aiku_main/service/MemberService.java
Labels: 기능개발

#125 스케줄 종료 시 다른 서비스에서 ScheduleCloseEvent만 핸들링 할 수 있도록 변경
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/BettingHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/ScheduleHandler.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
Labels: 리팩토링

#127 일부 수정사항 배포
  aiku/aiku-common/src/main/java/common/domain/member/Member.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/BettingHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/ScheduleHandler.java
  aiku/aiku-main/src/main/java/aiku_main/service/LoginService.java
  aiku/aiku-main/src/main/java/aiku_main/service/MemberService.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
Labels: 버그수정, 배포

#128 ScheduleAutoCloseEvent 의존 수정
  .gitignore
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/BettingHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/RacingHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/TeamHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/TitleHandler.java
  aiku/aiku-main/src/main/resources/application.yml
Labels: 버그수정

#129 배포 에러 해결
  .gitignore
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/BettingHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/RacingHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/TeamHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/TitleHandler.java
  aiku/aiku-main/src/main/resources/application.yml
Labels: 배포
