Repository AiKU-Dev/Backend, pull requests merged in 2024-09, with the labels that each got.

#7 이벤트 관련 엔티티 추가
  .gitignore
  .idea/.gitignore
  aiku/aiku-common/src/main/java/common/domain/event/CommonEvent.java
  aiku/aiku-common/src/main/java/common/domain/event/RecommendEvent.java
  aiku/aiku-common/src/main/java/common/domain/log/EventLog.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/EventValue.java
Labels: 기능개발

#8 feat : 스케줄 등록, 수정 서비스 로직 추가
  aiku/aiku-common/src/main/java/common/domain/Schedule.java
  aiku/aiku-common/src/main/java/common/domain/ScheduleMember.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/MemberValue.java
  aiku/aiku-common/src/main/java/common/exception/BaseExceptionImpl.java
  aiku/aiku-common/src/main/java/common/exception/NotEnoughPoint.java
  aiku/aiku-common/src/main/java/common/response/status/BaseErrorCode.java
  aiku/aiku-common/src/test/java/common/domain/ScheduleTest.java
  aiku/aiku-main/src/main/java/aiku_main/MainConfiguration.java
  aiku/aiku-main/src/main/java/aiku_main/SpringMainApplication.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/PointChangeEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/PointChangeReason.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/PointChangeType.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/PointChangeEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/controller/ScheduleController.java
  aiku/aiku-main/src/main/java/aiku_main/dto/ScheduleAddDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleRepository.java
  aiku/aiku-main/src/main/java/aiku_main/scheduler/ScheduleScheduler.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TeamServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/ScheduleServiceTest.java
Labels: 기능개발

#14 베팅 기능 개발 및 통합 테스트
  aiku/aiku-common/src/main/java/common/domain/Betting.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/ScheduleMemberValue.java
  aiku/aiku-common/src/main/java/common/response/status/BaseErrorCode.java
  aiku/aiku-common/src/test/java/common/domain/BettingTest.java
  aiku/aiku-main/src/main/java/aiku_main/controller/BettingController.java
  aiku/aiku-main/src/main/java/aiku_main/dto/BettingAddDto.java
  aiku/aiku-main/src/main/java/aiku_main/exception/CanNotBettingException.java
  aiku/aiku-main/src/main/java/aiku_main/repository/BettingRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/BettingRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/BettingRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/BettingService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/BettingServiceIntegrationTest.java
Labels: 기능개발

#17 외부 에그리게이트 참조를 위한 value object 리팩토링
  aiku/aiku-common/.DS_Store
  aiku/aiku-common/src/.DS_Store
  aiku/aiku-common/src/main/.DS_Store
  aiku/aiku-common/src/main/java/.DS_Store
  aiku/aiku-common/src/main/java/common/.DS_Store
  aiku/aiku-common/src/main/java/common/domain/Schedule.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/BettingValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/EventValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/MemberValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/PaymentValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/RacingValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/ScheduleValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/ShopProductValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/TeamValue.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/PointChangeEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/ScheduleExitEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/TeamExitEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/PointChangeEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/ScheduleEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/TeamEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/service/BettingService.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/BettingServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TeamServiceIntegrationTest.java
Labels: 리팩토링

#18 깍두기/유료 참가자와 스케줄장에 대한 로직 추가 및 그 외 로직 추가
  aiku/aiku-common/src/main/java/common/domain/schedule/Schedule.java
  aiku/aiku-common/src/main/java/common/domain/schedule/ScheduleMember.java
  aiku/aiku-common/src/main/java/common/domain/schedule/ScheduleResult.java
  aiku/aiku-common/src/main/java/common/domain/team/Team.java
  aiku/aiku-common/src/main/java/common/domain/team/TeamMember.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/ScheduleMemberValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/ScheduleValue.java
  aiku/aiku-common/src/main/java/common/exception/PaidMemberLimitException.java
  aiku/aiku-common/src/main/java/common/response/status/BaseErrorCode.java
  aiku/aiku-common/src/test/java/common/domain/BettingTest.java
  aiku/aiku-common/src/test/java/common/domain/ScheduleTest.java
  aiku/aiku-common/src/test/java/common/domain/TeamTest.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/PointChangeReason.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/ScheduleAutoCloseEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/ScheduleCloseEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/ScheduleExitEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/ScheduleOpenEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/BettingHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/ScheduleHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/ScheduleEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/TeamEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/dto/ScheduleDetailResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/TeamScheduleListEachResDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/BettingRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/BettingRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleReadRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamReadRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/scheduler/ScheduleScheduler.java
  aiku/aiku-main/src/main/java/aiku_main/service/BettingService.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/BettingServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TeamServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/ScheduleServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/TeamServiceTest.java
Labels: 기능개발

#22 Controller에서 Client request body에 대한 유효성을 검증한다.
  aiku/aiku-main/src/main/java/aiku_main/MainConfiguration.java
  aiku/aiku-main/src/main/java/aiku_main/controller/BettingController.java
  aiku/aiku-main/src/main/java/aiku_main/controller/ScheduleController.java
  aiku/aiku-main/src/main/java/aiku_main/controller/TeamController.java
  aiku/aiku-main/src/main/java/aiku_main/controller/validation/ValidPointAmount.java
  aiku/aiku-main/src/main/java/aiku_main/controller/validation/ValidPointAmountValidator.java
  aiku/aiku-main/src/main/java/aiku_main/controller/validation/ValidScheduleTime.java
  aiku/aiku-main/src/main/java/aiku_main/controller/validation/ValidScheduleTimeValidator.java
  aiku/aiku-main/src/main/java/aiku_main/dto/BettingAddDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/LocationDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/ScheduleAddDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/ScheduleEnterDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/ScheduleUpdateDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/TeamAddDto.java
  aiku/aiku-main/src/test/java/aiku_main/controller/BettingControllerTest.java
  aiku/aiku-main/src/test/java/aiku_main/controller/ScheduleControllerTest.java
  aiku/aiku-main/src/test/java/aiku_main/controller/TeamControllerTest.java
  aiku/build.gradle
Labels: 기능개발

#24 그룹 지각 랭킹 분석 개발
  aiku/aiku-common/src/main/java/common/domain/schedule/Schedule.java
  aiku/aiku-common/src/main/java/common/domain/schedule/ScheduleResult.java
  aiku/aiku-common/src/main/java/common/domain/team/Team.java
  aiku/aiku-common/src/main/java/common/domain/team/TeamResult.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/ScheduleValue.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/domain/TeamLateTimeResult.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/domain/TeamResultMember.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/ScheduleAutoCloseEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/ScheduleOpenEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/BettingHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/ScheduleHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/TeamHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/ScheduleEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/dto/MemberProfileResDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamReadRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamReadRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/scheduler/ScheduleScheduler.java
  aiku/aiku-main/src/main/java/aiku_main/service/BettingService.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/BettingServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TeamServiceIntegrationTest.java
Labels: 기능개발, 리팩토링

#26 성공 응답 메세지 포맷 리팩토링, 페이징 방식 변경
  aiku/aiku-common/src/main/java/common/response/BaseResponse.java
  aiku/aiku-common/src/main/java/common/response/status/BaseCode.java
  aiku/aiku-main/src/main/java/aiku_main/controller/BettingController.java
  aiku/aiku-main/src/main/java/aiku_main/controller/ScheduleController.java
  aiku/aiku-main/src/main/java/aiku_main/controller/TeamController.java
  aiku/aiku-main/src/main/java/aiku_main/dto/DataResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/MemberScheduleListResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/TeamScheduleListResDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleReadRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleReadRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamReadRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamReadRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TeamServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/TeamServiceTest.java
Labels: 리팩토링
