Repository AiKU-Dev/Backend, pull requests merged in 2024-10, with the labels that each got.

#27 그룹 베팅 결과 분석에 관한 로직 개발
  aiku/aiku-common/src/main/java/common/domain/Betting.java
  aiku/aiku-common/src/main/java/common/domain/schedule/Schedule.java
  aiku/aiku-common/src/main/java/common/domain/team/Team.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/domain/TeamBettingResult.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/domain/TeamResultMember.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/BettingHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/ScheduleHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/TeamHandler.java
  aiku/aiku-main/src/main/java/aiku_main/controller/ScheduleController.java
  aiku/aiku-main/src/main/java/aiku_main/controller/TeamController.java
  aiku/aiku-main/src/main/java/aiku_main/repository/BettingReadRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/BettingReadRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/BettingRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/BettingRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamReadRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamReadRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/dto/TeamBettingResultMemberDto.java
  aiku/aiku-main/src/main/java/aiku_main/service/BettingService.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/BettingServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TeamServiceIntegrationTest.java
Labels: 기능개발

#31 Title을 별도의 엔티티로 분리
  aiku/aiku-common/src/main/java/common/domain/Title.java
  aiku/aiku-common/src/main/java/common/domain/member/Member.java
  aiku/aiku-common/src/main/java/common/domain/title/Title.java
  aiku/aiku-common/src/main/java/common/domain/title/TitleMember.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/TitleMemberValue.java
  aiku/aiku-main/src/main/java/aiku_main/repository/MemberRepository.java
Labels: 리팩토링

#34 타이틀, 로그아웃, 권한 관리 등 유저와 관련된 기능 추가
  .gitignore
  aiku/aiku-common/src/main/java/common/domain/ServiceAgreement.java
  aiku/aiku-common/src/main/java/common/domain/member/Member.java
  aiku/aiku-common/src/main/java/common/domain/member/MemberProfile.java
  aiku/aiku-main/src/main/java/aiku_main/controller/MemberController.java
  aiku/aiku-main/src/main/java/aiku_main/dto/AuthorityResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/AuthorityUpdateDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/MemberResDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/MemberUpdateDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/TitleMemberResDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/MemberReadRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/MemberReadRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/MemberRepository.java
  aiku/aiku-main/src/main/java/aiku_main/service/MemberRegisterService.java
  aiku/aiku-main/src/main/java/aiku_main/service/MemberService.java
Labels: 기능개발

#36 Common 모듈에서 Security 의존 제거
  aiku/aiku-common/src/main/java/common/domain/member/Member.java
  aiku/aiku-gateway/build.gradle
  aiku/aiku-gateway/src/main/java/gateway/security/MemberAdaptor.java
  aiku/aiku-gateway/src/main/java/gateway/service/CustomMemberDetailsService.java
  aiku/aiku-main/build.gradle
  aiku/build.gradle
Labels: 리팩토링

#37 TeamService, ScheduleService, BettingService 리팩토링
  aiku/aiku-common/src/main/java/common/domain/Betting.java
  aiku/aiku-common/src/main/java/common/domain/schedule/Schedule.java
  aiku/aiku-common/src/main/java/common/domain/schedule/ScheduleMember.java
  aiku/aiku-common/src/main/java/common/domain/team/Team.java
  aiku/aiku-common/src/main/java/common/response/status/BaseErrorCode.java
  aiku/aiku-common/src/test/java/common/domain/BettingTest.java
  aiku/aiku-common/src/test/java/common/domain/TeamTest.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/PointChangeReason.java
  aiku/aiku-main/src/main/java/aiku_main/exception/BettingException.java
  aiku/aiku-main/src/main/java/aiku_main/exception/CanNotBettingException.java
  aiku/aiku-main/src/main/java/aiku_main/exception/ScheduleException.java
  aiku/aiku-main/src/main/java/aiku_main/exception/TeamException.java
  aiku/aiku-main/src/main/java/aiku_main/repository/BettingRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleReadRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamReadRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamReadRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/BettingService.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/BettingServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TeamServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/ScheduleServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/TeamServiceTest.java
Labels: 리팩토링

#39 AWS RDS연결 및 Database를 MySql로 변경
  aiku/aiku-alarm/src/main/java/alarm/SpringAlarmApplication.java
  aiku/aiku-alarm/src/main/resources/application.yml
  aiku/aiku-common/src/main/java/common/TestBean.java
  aiku/aiku-gateway/src/main/java/gateway/SpringGatewayApplication.java
  aiku/aiku-gateway/src/main/resources/application.yml
  aiku/aiku-main/src/main/java/aiku_main/SpringMainApplication.java
  aiku/aiku-main/src/main/resources/application.yml
  aiku/aiku-main/src/test/resources/application.yml
  aiku/aiku-map/src/main/java/map/SpringMapApplication.java
  aiku/aiku-map/src/main/resources/application.yml
  aiku/aiku-payment/src/main/java/payment/SpringPaymentApplication.java
  aiku/aiku-payment/src/main/resources/application.yml
  aiku/build.gradle
Labels: 기능개발

#41 h2→mysql 변경으로 인한 내장 함수 변경
  aiku/aiku-main/src/main/java/aiku_main/repository/BettingReadRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/BettingRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/MemberReadRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleReadRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamRepositoryCustomImpl.java
Labels: 기능개발, 리팩토링

#42 이메일 전송 로직 & 칭호 검증 로직 작성
  aiku/aiku-common/src/main/java/common/response/status/BaseErrorCode.java
  aiku/aiku-main/build.gradle
  aiku/aiku-main/src/main/java/aiku_main/SpringMainApplication.java
  aiku/aiku-main/src/main/java/aiku_main/controller/EmailSendController.java
  aiku/aiku-main/src/main/java/aiku_main/controller/MemberController.java
  aiku/aiku-main/src/main/java/aiku_main/dto/GmailCredential.java
  aiku/aiku-main/src/main/java/aiku_main/dto/GoogleTokenResponse.java
  aiku/aiku-main/src/main/java/aiku_main/dto/InquiryDto.java
  aiku/aiku-main/src/main/java/aiku_main/exception/TitleException.java
  aiku/aiku-main/src/main/java/aiku_main/gmail/GmailAPIProvider.java
  aiku/aiku-main/src/main/java/aiku_main/repository/MemberReadRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/MemberReadRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/security/SecurityConfig.java
  aiku/aiku-main/src/main/java/aiku_main/service/EmailService.java
  aiku/aiku-main/src/main/java/aiku_main/service/MemberService.java
  aiku/aiku-main/src/main/resources/application.yml
  aiku/aiku-main/src/test/resources/application.yml
Labels: 기능개발

#44 Kafka 연결 및 producer 테스트
  aiku/aiku-common/src/main/java/common/domain/schedule/Schedule.java
  aiku/aiku-common/src/main/java/common/exception/JsonParseException.java
  aiku/aiku-common/src/main/java/common/kafka/AlarmMessage.java
  aiku/aiku-common/src/main/java/common/kafka/AlarmMessageType.java
  aiku/aiku-common/src/main/java/common/kafka/KafkaTopic.java
  aiku/aiku-common/src/main/java/common/response/status/BaseErrorCode.java
  aiku/aiku-main/src/main/java/aiku_main/controller/MemberController.java
  aiku/aiku-main/src/main/java/aiku_main/kafka/KafkaProducerService.java
  aiku/aiku-main/src/main/java/aiku_main/repository/MemberReadRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleReadRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleReadRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/BettingService.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/resources/application.yml
  aiku/aiku-main/src/test/java/aiku_main/integration_test/BettingServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/kafka/KafkaProducerServiceTest.java
  aiku/aiku-main/src/test/resources/application.yml
Labels: 기능개발

#45 멤버 로직 리팩토링 및 약관 로직 작성
  aiku/aiku-common/src/main/java/common/domain/MemberTerm.java
  aiku/aiku-common/src/main/java/common/domain/ServiceAgreement.java
  aiku/aiku-common/src/main/java/common/domain/Term.java
  aiku/aiku-common/src/main/java/common/domain/TermStatus.java
  aiku/aiku-common/src/main/java/common/domain/TermTitle.java
  aiku/aiku-common/src/main/java/common/domain/member/Member.java
  aiku/aiku-common/src/main/java/common/domain/member/MemberProfile.java
  aiku/aiku-common/src/main/java/common/domain/title/Title.java
  aiku/aiku-common/src/main/java/common/domain/title/TitleMember.java
  aiku/aiku-main/src/main/java/aiku_main/controller/EmailSendController.java
  aiku/aiku-main/src/main/java/aiku_main/controller/MemberController.java
  aiku/aiku-main/src/main/java/aiku_main/controller/TermController.java
  aiku/aiku-main/src/main/java/aiku_main/dto/TermResDto.java
  aiku/aiku-main/src/main/java/aiku_main/exception/NoSuchTermException.java
  aiku/aiku-main/src/main/java/aiku_main/repository/MemberReadRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/MemberReadRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TermRepository.java
  aiku/aiku-main/src/main/java/aiku_main/service/EmailService.java
  aiku/aiku-main/src/main/java/aiku_main/service/MemberRegisterService.java
  aiku/aiku-main/src/main/java/aiku_main/service/MemberService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TermService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/MemberRegisterServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/MemberServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TermServiceTest.java
  aiku/aiku-main/src/test/resources/application-test.yml
Labels: 기능개발, 리팩토링

#48 AlarmMessage 추상화
  aiku/aiku-common/src/main/java/common/kafka/AlarmMessage.java
Labels: 리팩토링

#53 사용자 개별 FCM 토큰 저장 및 수정 로직 작성
  aiku/aiku-common/src/main/java/common/domain/member/Member.java
  aiku/aiku-common/src/main/java/common/response/status/BaseErrorCode.java
  aiku/aiku-main/src/main/java/aiku_main/controller/FirebaseController.java
  aiku/aiku-main/src/main/java/aiku_main/dto/FirebaseTokenDto.java
  aiku/aiku-main/src/main/java/aiku_main/exception/FcmTokenDuplicateException.java
  aiku/aiku-main/src/main/java/aiku_main/exception/NoFcmTokenException.java
  aiku/aiku-main/src/main/java/aiku_main/service/MemberFirebaseService.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/MemberFirebaseServiceTest.java
Labels: 기능개발

#54 alarm 토픽의 메세지 AlarmMessage클래스 리팩토링 및 변경에 따른 코드 수정
  aiku/aiku-common/src/main/java/common/kafka_message/KafkaTopic.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/AlarmMemberInfo.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/AlarmMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/AlarmMessageType.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/ScheduleAlarmMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/ScheduleMemberAlarmMessage.java
  aiku/aiku-main/src/main/java/aiku_main/kafka/KafkaProducerService.java
  aiku/aiku-main/src/main/java/aiku_main/repository/TeamRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/test/java/aiku_main/kafka/KafkaProducerServiceTest.java
  aiku/aiku-main/src/test/resources/application-test.yml
Labels: 기능개발, 리팩토링

#57 Kafka scheudule-close, schedule-arrival consume 로직 개발
  aiku/aiku-common/src/main/java/common/domain/schedule/Schedule.java
  aiku/aiku-common/src/main/java/common/kafka_message/KafkaTopic.java
  aiku/aiku-common/src/main/java/common/kafka_message/ScheduleArrivalMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/ScheduleCloseMessage.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/ScheduleAutoCloseEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/BettingHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/ScheduleHandler.java
  aiku/aiku-main/src/main/java/aiku_main/kafka/KafkaConsumerService.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/resources/application.yml
  aiku/aiku-main/src/test/java/aiku_main/integration_test/BettingServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/kafka/KafkaConsumerServiceTest.java
  aiku/aiku-main/src/test/resources/application.yml
Labels: 기능개발

#58 지도 관련 로직 추가
  .gitignore
  aiku/aiku-common/src/main/java/common/domain/Racing.java
  aiku/aiku-common/src/main/java/common/domain/schedule/Schedule.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/ScheduleMemberValue.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/AlarmMemberInfo.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/AlarmMessageType.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/ArrivalAlarmMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/AskRacingMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/EmojiMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/LocationAlarmMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/PointChangedMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/RacingAutoDeletedMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/RacingDeniedMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/RacingStartMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/ScheduleClosedMessage.java
  aiku/aiku-common/src/main/java/common/response/status/BaseErrorCode.java
  aiku/aiku-map/src/main/java/map/SpringMapApplication.java
  aiku/aiku-map/src/main/java/map/application_event/domain/RacingInfo.java
  aiku/aiku-map/src/main/java/map/application_event/event/AskRacingEvent.java
  aiku/aiku-map/src/main/java/map/application_event/event/RacingStatusNotChangedEvent.java
  aiku/aiku-map/src/main/java/map/application_event/handler/RacingHandler.java
  aiku/aiku-map/src/main/java/map/application_event/publisher/RacingEventPublisher.java
  aiku/aiku-map/src/main/java/map/controller/MapController.java
  aiku/aiku-map/src/main/java/map/controller/validation/ValidPointAmount.java
  aiku/aiku-map/src/main/java/map/controller/validation/ValidPointAmountValidator.java
  aiku/aiku-map/src/main/java/map/dto/DataResDto.java
  aiku/aiku-map/src/main/java/map/dto/EmojiDto.java
  aiku/aiku-map/src/main/java/map/dto/EmojiType.java
  aiku/aiku-map/src/main/java/map/dto/MemberArrivalDto.java
  aiku/aiku-map/src/main/java/map/dto/MemberProfileDto.java
  aiku/aiku-map/src/main/java/map/dto/RacerResDto.java
  aiku/aiku-map/src/main/java/map/dto/RacingAddDto.java
  aiku/aiku-map/src/main/java/map/dto/RacingResDto.java
  aiku/aiku-map/src/main/java/map/dto/RealTimeLocationDto.java
  aiku/aiku-map/src/main/java/map/exception/DuplicateRacingException.java
  aiku/aiku-map/src/main/java/map/exception/MemberNotFoundException.java
  aiku/aiku-map/src/main/java/map/exception/MemberNotInRacingException.java
  aiku/aiku-map/src/main/java/map/exception/NoSuchRacingException.java
  aiku/aiku-map/src/main/java/map/exception/NotEnoughPointException.java
  aiku/aiku-map/src/main/java/map/exception/ScheduleException.java
  aiku/aiku-map/src/main/java/map/kafka/KafkaProducerService.java
  aiku/aiku-map/src/main/java/map/repository/MemberQueryRepository.java
  aiku/aiku-map/src/main/java/map/repository/MemberQueryRepositoryImpl.java
  aiku/aiku-map/src/main/java/map/repository/MemberRepository.java
  aiku/aiku-map/src/main/java/map/repository/RacingQueryRepository.java
  aiku/aiku-map/src/main/java/map/repository/RacingQueryRepositoryImpl.java
  aiku/aiku-map/src/main/java/map/repository/RacingRepository.java
  aiku/aiku-map/src/main/java/map/repository/ScheduleQueryRepository.java
  aiku/aiku-map/src/main/java/map/repository/ScheduleQueryRepositoryImpl.java
  aiku/aiku-map/src/main/java/map/repository/ScheduleRepository.java
  aiku/aiku-map/src/main/java/map/scheduler/RacingScheduler.java
  aiku/aiku-map/src/main/java/map/service/MapService.java
  aiku/aiku-map/src/main/java/map/service/RacingService.java
  aiku/aiku-map/src/main/resources/application.yml
  aiku/aiku-map/src/test/java/map/service/MapServiceTest.java
  aiku/aiku-map/src/test/java/map/service/RacingServiceTest.java
  aiku/aiku-map/src/test/java/map/service/TeamRepository.java
  aiku/aiku-map/src/test/resources/application.yml
Labels: 기능개발

#59 Spring Cloud Gateway를 통한 MSA 라우팅
  aiku/aiku-alarm/build.gradle
  aiku/aiku-common/build.gradle
  aiku/aiku-common/src/main/java/common/response/BaseErrorResponse.java
  aiku/aiku-gateway/build.gradle
  aiku/aiku-gateway/src/main/java/gateway/SpringGatewayApplication.java
  aiku/aiku-gateway/src/main/java/gateway/dto/member/Member.java
  aiku/aiku-gateway/src/main/java/gateway/dto/member/MemberRole.java
  aiku/aiku-gateway/src/main/java/gateway/exception/JwtAccessDeniedException.java
  aiku/aiku-gateway/src/main/java/gateway/exception/MemberNotFoundException.java
  aiku/aiku-gateway/src/main/java/gateway/repository/MemberQueryRepository.java
  aiku/aiku-gateway/src/main/java/gateway/repository/MemberQueryRepositoryImpl.java
  aiku/aiku-gateway/src/main/java/gateway/repository/MemberReadRepository.java
  aiku/aiku-gateway/src/main/java/gateway/security/JwtAccessDeniedHandler.java
  aiku/aiku-gateway/src/main/java/gateway/security/JwtAuthenticationFilter.java
  aiku/aiku-gateway/src/main/java/gateway/security/JwtExceptionFilter.java
  aiku/aiku-gateway/src/main/java/gateway/security/MemberAdaptor.java
  aiku/aiku-gateway/src/main/java/gateway/security/OpenEntityManagerConfig.java
  aiku/aiku-gateway/src/main/java/gateway/security/SecurityConfig.java
  aiku/aiku-gateway/src/main/java/gateway/service/CustomMemberDetailsService.java
  aiku/aiku-gateway/src/main/resources/application.yml
  aiku/aiku-map/build.gradle
  aiku/aiku-payment/build.gradle
  aiku/build.gradle
Labels: 기능개발

#61 테스트 설정 파일 변경
  .gitignore
  aiku/aiku-common/src/main/java/common/domain/schedule/ScheduleResult.java
  aiku/aiku-common/src/main/java/common/domain/team/TeamResult.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/MemberFirebaseServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/MemberRegisterServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/MemberServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TermServiceTest.java
  aiku/aiku-main/src/test/resources/application-test.yml
  aiku/aiku-main/src/test/resources/application.yml
  aiku/aiku-map/src/test/java/map/service/MapServiceTest.java
  aiku/aiku-map/src/test/java/map/service/RacingServiceTest.java
  aiku/aiku-map/src/test/resources/application.yml
Labels: 리팩토링

#66 Access-Member-Id헤더로 요청 멤버 정보 처리 로직 추가
  aiku/aiku-main/src/main/java/aiku_main/controller/BettingController.java
  aiku/aiku-main/src/main/java/aiku_main/controller/ScheduleController.java
  aiku/aiku-main/src/main/java/aiku_main/controller/TeamController.java
  aiku/aiku-main/src/main/java/aiku_main/service/BettingService.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java
  aiku/aiku-main/src/test/java/aiku_main/controller/BettingControllerTest.java
  aiku/aiku-main/src/test/java/aiku_main/controller/ScheduleControllerTest.java
  aiku/aiku-main/src/test/java/aiku_main/controller/TeamControllerTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/BettingServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/integration_test/TeamServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/ScheduleServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/TeamServiceTest.java
Labels: 기능개발

#68 배포를 위한 yml파일 수정
  aiku/aiku-alarm/src/main/resources/application.yml
  aiku/aiku-gateway/src/main/resources/application.yml
  aiku/aiku-main/src/main/resources/application.yml
  aiku/aiku-map/src/main/resources/application.yml
  aiku/aiku-payment/src/main/resources/application.yml
Labels: 리팩토링

#71 gateway, main, alarm, map모듈에 Dockerfile 생성
  aiku/aiku-alarm/Dockerfile
  aiku/aiku-gateway/Dockerfile
  aiku/aiku-main/Dockerfile
  aiku/aiku-map/Dockerfile
Labels: 빌드수정

#73 레이싱 생성 시 ScheduleMember의 id를 이용하도록 수정
  aiku/aiku-common/src/main/java/common/domain/Racing.java
  aiku/aiku-map/src/main/java/map/repository/ScheduleQueryRepository.java
  aiku/aiku-map/src/main/java/map/repository/ScheduleQueryRepositoryImpl.java
  aiku/aiku-map/src/main/java/map/service/RacingService.java
Labels: 버그수정

#76 공개키를 파싱하지 못하는 문제 해결
  aiku/aiku-main/src/main/java/aiku_main/dto/MemberProfileDto.java
  aiku/aiku-main/src/main/java/aiku_main/oauth/dto/OIDCPublicKeyDto.java
  aiku/aiku-main/src/main/java/aiku_main/security/CustomUserDetailsService.java
  aiku/aiku-main/src/main/java/aiku_main/security/MemberAdaptor.java
  aiku/aiku-main/src/main/java/aiku_main/service/MemberRegisterService.java
Labels: 버그수정

#77 멤버 등록 오류 수정
  aiku/aiku-main/src/main/java/aiku_main/dto/MemberProfileDto.java
  aiku/aiku-main/src/main/java/aiku_main/oauth/dto/OIDCPublicKeyDto.java
  aiku/aiku-main/src/main/java/aiku_main/security/CustomUserDetailsService.java
  aiku/aiku-main/src/main/java/aiku_main/security/MemberAdaptor.java
  aiku/aiku-main/src/main/java/aiku_main/service/MemberRegisterService.java
Labels: 배포

#79 aiku-gateway의 멤버 레파지토리 필드 오기재 수정
  aiku/aiku-gateway/src/main/java/gateway/repository/MemberQueryRepositoryImpl.java
Labels: 버그수정, 배포

#82 그룹, 스케줄 오류 수정
  aiku/aiku-main/src/main/java/aiku_main/controller/TeamController.java
  aiku/aiku-main/src/main/java/aiku_main/dto/LocationDto.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java
Labels: 버그수정

#83 Postman 테스트 중 그룹, 스케줄 오류 수정 적용
  aiku/aiku-main/src/main/java/aiku_main/controller/TeamController.java
  aiku/aiku-main/src/main/java/aiku_main/dto/LocationDto.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java
Labels: 버그수정, 배포

#86 로깅을 위한 스레드 별 고유 아이디 지정 코드 반영
  aiku/aiku-alarm/src/main/java/alarm/WebConfiguration.java
  aiku/aiku-alarm/src/main/java/alarm/filter/MdcFilter.java
  aiku/aiku-alarm/src/main/java/alarm/filter/RequestLogInterceptor.java
  aiku/aiku-alarm/src/main/resources/application.yml
  aiku/aiku-common/src/main/java/common/response/BaseResponse.java
  aiku/aiku-main/src/main/java/aiku_main/WebConfiguration.java
  aiku/aiku-main/src/main/java/aiku_main/dto/SignInTokenResDto.java
  aiku/aiku-main/src/main/java/aiku_main/filter/MdcFilter.java
  aiku/aiku-main/src/main/java/aiku_main/filter/RequestLogInterceptor.java
  aiku/aiku-main/src/main/java/aiku_main/filter/security/CustomUserDetailsService.java
  aiku/aiku-main/src/main/java/aiku_main/filter/security/JwtToken.java
  aiku/aiku-main/src/main/java/aiku_main/filter/security/JwtTokenProvider.java
  aiku/aiku-main/src/main/java/aiku_main/filter/security/MemberAdaptor.java
  aiku/aiku-main/src/main/java/aiku_main/filter/security/SecurityConfig.java
  aiku/aiku-main/src/main/java/aiku_main/service/LoginService.java
  aiku/aiku-main/src/main/resources/application.yml
  aiku/aiku-map/src/main/java/map/WebConfiguration.java
  aiku/aiku-map/src/main/java/map/filter/MdcFilter.java
  aiku/aiku-map/src/main/java/map/filter/RequestLogInterceptor.java
  aiku/aiku-map/src/main/resources/application.yml
Labels: 배포

#87 Filter Config설정 오류 수정
  aiku/aiku-alarm/src/main/java/alarm/WebConfiguration.java
  aiku/aiku-map/src/main/java/map/WebConfiguration.java
Labels: 버그수정

#88 aiku-map 빌드 오류 수정
  aiku/aiku-alarm/src/main/java/alarm/WebConfiguration.java
  aiku/aiku-map/src/main/java/map/WebConfiguration.java
Labels: 버그수정, 배포

#90 Team, Schedule, BettingException에 대한 핸들러 개발
  aiku/aiku-common/src/main/java/common/response/BaseErrorResponse.java
  aiku/aiku-main/src/main/java/aiku_main/MainConfiguration.java
  aiku/aiku-main/src/main/java/aiku_main/exception/MainExceptionHandler.java
Labels: 기능개발

#91 구체화한 ExceptionHandler 적용
  aiku/aiku-common/src/main/java/common/response/BaseErrorResponse.java
  aiku/aiku-main/src/main/java/aiku_main/MainConfiguration.java
  aiku/aiku-main/src/main/java/aiku_main/exception/MainExceptionHandler.java
Labels: 배포
