Repository AiKU-Dev/Backend, pull requests merged in 2025-01, with the labels that each got.

#153 포인트 증감에 대한 보상 트랜잭션 구현
  .gitignore
  aiku/aiku-alarm/src/main/java/alarm/util/AlarmMessageConverter.java
  aiku/aiku-alarm/src/main/java/alarm/util/AlarmMessageMapper.java
  aiku/aiku-common/src/main/java/common/domain/Racing.java
  aiku/aiku-common/src/main/java/common/domain/Status.java
  aiku/aiku-common/src/main/java/common/kafka_message/PointChangeReason.java
  aiku/aiku-common/src/main/java/common/kafka_message/RacingPointChangedFailedMessage.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/AlarmMessageType.java
  aiku/aiku-common/src/main/java/common/kafka_message/alarm/PointErrorMessage.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/PointChangeFailEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/PointChangeEventHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/PointChangeFailEventHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/PointChangeFailEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/exception/MainExceptionHandler.java
  aiku/aiku-main/src/main/java/aiku_main/exception/PointChangeFailException.java
  aiku/aiku-main/src/main/java/aiku_main/repository/MemberRepository.java
  aiku/aiku-main/src/main/java/aiku_main/service/MemberPointChangeFacade.java
  aiku/aiku-main/src/main/java/aiku_main/service/PointChangeFailSagaService.java
  aiku/aiku-main/src/main/java/aiku_main/service/PointLogService.java
  aiku/aiku-main/src/main/java/aiku_main/service/strategy/PointChangeReasonMapping.java
  aiku/aiku-main/src/main/java/aiku_main/service/strategy/RacingRollbackStrategy.java
  aiku/aiku-main/src/main/java/aiku_main/service/strategy/RollbackProcessor.java
  aiku/aiku-main/src/main/java/aiku_main/service/strategy/RollbackStrategy.java
  aiku/aiku-main/src/main/java/aiku_main/service/strategy/ScheduleEnterRollbackStrategy.java
  aiku/aiku-main/src/test/java/aiku_main/service/RacingServiceTest.java
  aiku/aiku-map/src/main/java/map/dto/ScheduleMemberResDto.java
  aiku/aiku-map/src/main/java/map/kafka/KafkaConsumerService.java
  aiku/aiku-map/src/main/java/map/repository/RacingCommandRepositoryCustom.java
  aiku/aiku-map/src/main/java/map/repository/RacingCommandRepositoryCustomImpl.java
  aiku/aiku-map/src/main/java/map/repository/ScheduleQueryRepository.java
  aiku/aiku-map/src/main/java/map/repository/ScheduleQueryRepositoryImpl.java
  aiku/aiku-map/src/main/java/map/service/RacingSagaService.java
  aiku/aiku-map/src/main/java/map/service/RacingService.java
  aiku/aiku-map/src/test/java/map/service/MapServiceTest.java
  aiku/aiku-map/src/test/java/map/service/RacingServiceTest.java
Labels: 기능개발

#155 도메인 값 객체에서 엔티티 참조 제거, Long타입의 id로 생성하게 끔 변경
  aiku/aiku-common/src/main/java/common/domain/value_reference/BettingValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/EventValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/MemberValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/PaymentValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/RacingValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/ScheduleMemberValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/ScheduleValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/ShopProductValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/TeamValue.java
  aiku/aiku-common/src/main/java/common/domain/value_reference/TitleMemberValue.java
Labels: 리팩토링

#157 application event에서 엔티티에 사용되는 값 객체 제거
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/PointChangeEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/PointChangeFailEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/ScheduleAutoCloseEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/ScheduleCloseEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/ScheduleExitEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/ScheduleOpenEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/TeamExitEvent.java
Labels: 리팩토링

#158 event publisher에 엔티티 관련 의존 제거 및 컴파일 오류 수정
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/BettingHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/ScheduleHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/TeamHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/PointChangeEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/PointChangeFailEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/ScheduleEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/TeamEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/repository/BettingQueryRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/BettingQueryRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/BettingService.java
  aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java
  aiku/aiku-main/src/test/java/aiku_main/service/BettingServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/ScheduleServiceTest.java
Labels: 리팩토링

#160 value object와 event 리팩토링에 따른 컴파일 오류 수정 완료
  aiku/aiku-main/src/main/java/aiku_main/scheduler/ScheduleScheduler.java
  aiku/aiku-main/src/test/java/aiku_main/service/BettingServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/ScheduleServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/TeamServiceIntegrationTest.java
Labels: 버그수정, 리팩토링
