Repository AiKU-Dev/Backend, pull requests merged in 2025-05, with the labels that each got.

#182 스케줄 결과 분석 리팩토링
  .github/workflows/gradle.yml
  aiku/aiku-common/src/main/java/common/util/ObjectMapperUtil.java
  aiku/aiku-gateway/src/main/java/gateway/repository/MemberQueryRepository.java
  aiku/aiku-gateway/src/main/java/gateway/repository/MemberQueryRepositoryImpl.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/BettingHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/RacingHandler.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/ScheduleHandler.java
  aiku/aiku-main/src/main/java/aiku_main/dto/betting/ScheduleBetting.java
  aiku/aiku-main/src/main/java/aiku_main/dto/betting/ScheduleBettingMember.java
  aiku/aiku-main/src/main/java/aiku_main/dto/racing/ScheduleRacing.java
  aiku/aiku-main/src/main/java/aiku_main/dto/racing/ScheduleRacingMember.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/result/betting/BettingResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/result/betting/BettingResultDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/result/betting/BettingResultMember.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/result/racing/RacingResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/result/racing/RacingResultDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/result/racing/RacingResultMember.java
  aiku/aiku-main/src/main/java/aiku_main/repository/betting/BettingRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/betting/BettingRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/racing/RacingRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/racing/RacingRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/RacingService.java
  aiku/aiku-main/src/main/java/aiku_main/service/betting/BettingService.java
  aiku/aiku-main/src/main/java/aiku_main/service/schedule/ScheduleResultAnalysisService.java
  aiku/aiku-main/src/main/java/aiku_main/service/schedule/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/strategy/BettingRollbackStrategy.java
  aiku/aiku-main/src/main/java/aiku_main/service/strategy/ScheduleEnterRollbackStrategy.java
  aiku/aiku-main/src/main/java/aiku_main/service/strategy/ScheduleRollbackStrategy.java
  aiku/aiku-main/src/main/java/aiku_main/service/team/TeamService.java
  aiku/aiku-main/src/test/java/aiku_main/service/BettingServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/MemberAccessTokenTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/RacingServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/ScheduleServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/schedule/ScheduleResultAnalysisServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/strategy/BettingRollbackStrategyTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/strategy/ScheduleRollbackStrategyTest.java
  aiku/aiku-map/src/test/java/map/service/MapServiceTest.java
  aiku/aiku-map/src/test/java/map/service/RacingServiceTest.java
Labels: 리팩토링

#184 허용된 요청의 경우 필터 로직을 수행하지 않도록 수정
  aiku/aiku-gateway/src/main/java/gateway/security/JwtAuthenticationFilter.java
  aiku/aiku-gateway/src/main/java/gateway/security/JwtSecurityUtils.java
  aiku/aiku-gateway/src/main/java/gateway/security/SecurityConfig.java
Labels: 버그수정

#185 게이트웨이에 수정된 경로 추가
  aiku/aiku-gateway/src/main/resources/application.yml
Labels: 버그수정

#187 팀 결과 분석 기획 변경에 따른 로직 수정 및 리팩토링
  aiku/aiku-common/src/main/java/common/domain/schedule/ScheduleMember.java
  aiku/aiku-common/src/main/java/common/domain/team/TeamResult.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/TeamHandler.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/TeamMemberResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/result/betting_odds/TeamBettingResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/result/betting_odds/TeamBettingResultDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/result/late_time/TeamLateTimeResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/result/late_time/TeamLateTimeResultDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/result/racing_odds/TeamRacingResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/result/racing_odds/TeamRacingResultDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/betting/BettingRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/betting/BettingRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/dto/TeamBettingResultMemberDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/dto/TeamRacingResultMemberDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/racing/RacingRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/racing/RacingRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/schedule/ScheduleRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/team/TeamRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/team/TeamRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/schedule/ScheduleResultAnalysisService.java
  aiku/aiku-main/src/main/java/aiku_main/service/team/TeamResultAnalysisService.java
  aiku/aiku-main/src/main/java/aiku_main/service/team/TeamService.java
  aiku/aiku-main/src/test/java/aiku_main/service/TeamServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/team/TeamResultAnalysisServiceTest.java
Labels: 기능개발, 리팩토링

#189 Gateway에서 인증 실패 발생한 경우 응답 및 로깅 방식 통일
  aiku/aiku-alarm/src/main/resources/application.yml
  aiku/aiku-gateway/src/main/java/gateway/exception/BaseErrorResponse.java
  aiku/aiku-gateway/src/main/java/gateway/exception/GlobalWebExceptionHandler.java
  aiku/aiku-gateway/src/main/java/gateway/security/JwtAccessDeniedHandler.java
  aiku/aiku-gateway/src/main/java/gateway/security/JwtExceptionFilter.java
  aiku/aiku-gateway/src/main/java/gateway/security/JwtToken.java
  aiku/aiku-gateway/src/main/java/gateway/security/SecurityConfig.java
  aiku/aiku-gateway/src/main/resources/application.yml
Labels: 버그수정, 기능개발

#190 스케줄 도착 결과 dto 패키지 분류
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/ScheduleArrivalResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/result/arrival_time/ScheduleArrivalResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/result/arrival_time/ScheduleArrivalResultDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/schedule/ScheduleRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/schedule/ScheduleRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/schedule/ScheduleResultAnalysisService.java
  aiku/aiku-main/src/test/java/aiku_main/service/schedule/ScheduleResultAnalysisServiceIntegrationTest.java
Labels: 리팩토링

#192 Gateway에서 인증 실패 응답 형식 리팩토링 배포
  aiku/aiku-alarm/src/main/resources/application.yml
  aiku/aiku-common/src/main/java/common/domain/schedule/ScheduleMember.java
  aiku/aiku-common/src/main/java/common/domain/team/TeamResult.java
  aiku/aiku-gateway/src/main/java/gateway/exception/BaseErrorResponse.java
  aiku/aiku-gateway/src/main/java/gateway/exception/GlobalWebExceptionHandler.java
  aiku/aiku-gateway/src/main/java/gateway/security/JwtAccessDeniedHandler.java
  aiku/aiku-gateway/src/main/java/gateway/security/JwtExceptionFilter.java
  aiku/aiku-gateway/src/main/java/gateway/security/JwtToken.java
  aiku/aiku-gateway/src/main/java/gateway/security/SecurityConfig.java
  aiku/aiku-gateway/src/main/resources/application.yml
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/TeamHandler.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/ScheduleArrivalResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/result/arrival_time/ScheduleArrivalResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/schedule/result/arrival_time/ScheduleArrivalResultDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/TeamMemberResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/result/betting_odds/TeamBettingResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/result/betting_odds/TeamBettingResultDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/result/late_time/TeamLateTimeResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/result/late_time/TeamLateTimeResultDto.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/result/racing_odds/TeamRacingResult.java
  aiku/aiku-main/src/main/java/aiku_main/dto/team/result/racing_odds/TeamRacingResultDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/betting/BettingRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/betting/BettingRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/dto/TeamBettingResultMemberDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/dto/TeamRacingResultMemberDto.java
  aiku/aiku-main/src/main/java/aiku_main/repository/racing/RacingRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/racing/RacingRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/schedule/ScheduleRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/schedule/ScheduleRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/schedule/ScheduleRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/team/TeamRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/team/TeamRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/service/schedule/ScheduleResultAnalysisService.java
  aiku/aiku-main/src/main/java/aiku_main/service/team/TeamResultAnalysisService.java
  aiku/aiku-main/src/main/java/aiku_main/service/team/TeamService.java
  aiku/aiku-main/src/test/java/aiku_main/service/TeamServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/schedule/ScheduleResultAnalysisServiceIntegrationTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/team/TeamResultAnalysisServiceTest.java
Labels: 배포

#193 ScheduleService, TeamService에서 커스텀 event publisher 제거
  aiku/aiku-common/src/main/java/common/domain/schedule/Schedule.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/ScheduleEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/TeamEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/service/schedule/ScheduleService.java
  aiku/aiku-main/src/main/java/aiku_main/service/team/TeamService.java
Labels: 리팩토링

#194 Map, Racing, MemberPoint에 대한 EventPublisher 제거
  aiku/aiku-main/src/main/java/aiku_main/application_event/publisher/PointChangeFailEventPublisher.java
  aiku/aiku-main/src/main/java/aiku_main/service/member/MemberPointChangeFacade.java
  aiku/aiku-map/src/main/java/map/application_event/publisher/RacingEventPublisher.java
  aiku/aiku-map/src/main/java/map/application_event/publisher/ScheduleEventPublisher.java
  aiku/aiku-map/src/main/java/map/kafka/KafkaConsumerService.java
  aiku/aiku-map/src/main/java/map/scheduler/RacingScheduler.java
  aiku/aiku-map/src/main/java/map/service/MapService.java
  aiku/aiku-map/src/main/java/map/service/RacingService.java
Labels: 리팩토링

#195 BettingService, ScheduleScheduler, KafkaConsumerService 에서 커스텀 Event Publisher제거
  aiku/aiku-main/src/main/java/aiku_main/kafka/KafkaConsumerService.java
  aiku/aiku-main/src/main/java/aiku_main/scheduler/ScheduleScheduler.java
  aiku/aiku-main/src/main/java/aiku_main/service/betting/BettingService.java
Labels: 리팩토링

#196 Map 모듈 EventHandler를 이벤트 관점으로 분리
  aiku/aiku-main/src/main/java/aiku_main/service/member/MemberRegisterService.java
  aiku/aiku-map/src/main/java/map/MapConfiguration.java
  aiku/aiku-map/src/main/java/map/SpringMapApplication.java
  aiku/aiku-map/src/main/java/map/application_event/handler/AskRacingEventHandler.java
  aiku/aiku-map/src/main/java/map/application_event/handler/MemberArrivalEventHandler.java
  aiku/aiku-map/src/main/java/map/application_event/handler/RacingStatusNotChangedEventHandler.java
  aiku/aiku-map/src/main/java/map/application_event/handler/ScheduleCloseEventHandler.java
  aiku/aiku-map/src/main/java/map/application_event/handler/ScheduleEventHandler.java
  aiku/aiku-map/src/main/java/map/repository/RacingCommandRepositoryCustomImpl.java
  aiku/aiku-map/src/main/java/map/service/MapService.java
  aiku/aiku-map/src/main/java/map/service/RacingService.java
Labels: 리팩토링

#206 aiku-main에서 스케줄 자동 종료에 대한 이벤트 구조 변화 및 Arrival 분리에 의한 로직 변경
  aiku/aiku-common/src/main/java/common/domain/schedule/Schedule.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/event/ScheduleAutoCloseEvent.java
  aiku/aiku-main/src/main/java/aiku_main/application_event/handler/ScheduleAutoCloseEventHandler.java
  aiku/aiku-main/src/main/java/aiku_main/kafka/KafkaConsumerService.java
  aiku/aiku-main/src/main/java/aiku_main/kafka/KafkaProducerService.java
  aiku/aiku-main/src/main/java/aiku_main/repository/arrival/ArrivalRepository.java
  aiku/aiku-main/src/main/java/aiku_main/repository/arrival/ArrivalRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/arrival/ArrivalRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/schedule/ScheduleRepositoryCustom.java
  aiku/aiku-main/src/main/java/aiku_main/repository/schedule/ScheduleRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/repository/team/TeamRepositoryCustomImpl.java
  aiku/aiku-main/src/main/java/aiku_main/scheduler/ScheduleScheduler.java
  aiku/aiku-main/src/main/java/aiku_main/service/schedule/ScheduleService.java
  aiku/aiku-main/src/test/java/aiku_main/service/ScheduleServiceTest.java
  aiku/aiku-main/src/test/java/aiku_main/service/TitleServiceTest.java
Labels: 기능개발, 리팩토링

#211 스케줄, 팀 도메인 단위 테스트 작성
  aiku/aiku-common/src/main/java/common/domain/betting/Betting.java
  aiku/aiku-common/src/main/java/common/domain/schedule/Schedule.java
  aiku/aiku-common/src/main/java/common/domain/schedule/ScheduleResult.java
  aiku/aiku-common/src/main/java/common/domain/team/Team.java
  aiku/aiku-common/src/test/java/common/domain/ScheduleTest.java
  aiku/aiku-common/src/test/java/common/domain/TeamTest.java
  aiku/aiku-common/src/test/java/common/domain/betting/BettingTest.java
  aiku/aiku-common/src/test/java/common/domain/schedule/ScheduleResultTest.java
  aiku/aiku-common/src/test/java/common/domain/team/TeamResultTest.java
  aiku/aiku-main/src/main/java/aiku_main/service/betting/BettingService.java
Labels: 테스트
